### ISSUE TITLE
Basic setup documentation

### ISSUE THREAD

**Issue by NagariaHussain** [NagariaHussain/waba_integration#3]
README

**Comment by asoral** [comment]
I am willing to do this, but I need some help before I start. For eg. How to generate verification token, etc.

**Comment by NagariaHussain** [comment]
> I am willing to do this, but I need some help before I start. For eg. How to generate verification token, etc.

Hey! This is good place to start: https://developers.facebook.com/docs/whatsapp/cloud-api/get-started

The user has to generate the credentials as above and put them in `WABA Settings` for setup.

**Comment by hicham-alsayed-ahmad** [comment]
hi, how to verification the web hook ? 
I meant the callback url !
<img width="870" alt="Screen Shot 2022-12-23 at 10 17 04 PM" src="https://user-images.githubusercontent.com/12430517/209389875-9cd6d4be-e80d-414d-b35e-c36d19e8dfeb.png">

**Comment by NagariaHussain** [comment]
Hi @hicham-alsayed-ahmad !

The callback URL will be:

```
<your-site-base-url>/api/method/waba_integration.api.webhook.handle
```
For instance:

```
https://htest.frappe.cloud/api/method/waba_integration.api.webhook.handle
```
